spring:
  application:
    name: crowdfunding
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crowdfunding
    username: root
    password: mika

  data:
    jdbc:
      dialect: mysql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 8080
